class Strings {
  Strings._();

  static String of(String key, String locale) {
    return _data[locale]?[key] ?? _data['ru']?[key] ?? key;
  }

  static const _data = <String, Map<String, String>>{
    'ru': {
      'app_title': 'Deutsche Verb',
      'verbs': 'Глаголы',
      'training': 'Тренировка',
      'profile': 'Профиль',
      'info': 'Инфо',
      'search': 'Поиск',
      'all': 'Все',
      'weak': 'Слабый',
      'strong': 'Сильный',
      'mixed': 'Смешанный',
      'weak_pl': 'Слабые',
      'strong_pl': 'Сильные',
      'mixed_pl': 'Смешанные',
      'no_verbs': 'Нет глаголов для тренировки',
      'no_verbs_filter': 'Нет глаголов по выбранным фильтрам',
      'repeat': 'Повторить',
      'know': 'Знаю',
      'reset_progress': 'Сбросить прогресс',
      'reset_title': 'Сбросить прогресс?',
      'reset_text': 'Весь прогресс изучения будет удален.',
      'cancel': 'Отмена',
      'reset': 'Сбросить',
      'learned_count': '{learned} / {total} глаголов изучено',
      'learned_by_level': 'Изучено по уровням',
      'dark_theme': 'Тёмная тема',
      'info_title': 'Информация',
      'info_desc': 'Приложение для изучения немецких глаголов с карточками и прогрессом.',
      'author': 'Автор',
      'author_name': 'Дронов Дмитрий',
      'author_desc': 'Разработчик и энтузиаст немецкого языка. Если у вас есть вопросы или предложения, посетите сайт автора.',
      'website': 'Сайт автора',
      'github_profile': 'GitHub профиль',
      'link': 'Ссылка',
      'language': 'Язык',
      'russian': 'Русский',
      'ukrainian': 'Українська',
      'update_available': 'Доступно обновление',
      'new_version': 'Новая версия:',
      'later': 'Позже',
      'update_now': 'Обновить',
      'open_releases': 'Открыть релиз',
    },
    'uk': {
      'app_title': 'Deutsche Verb',
      'verbs': 'Дієслова',
      'training': 'Тренування',
      'profile': 'Профіль',
      'info': 'Інфо',
      'search': 'Пошук',
      'all': 'Всі',
      'weak': 'Слабкий',
      'strong': 'Сильний',
      'mixed': 'Змішаний',
      'weak_pl': 'Слабкі',
      'strong_pl': 'Сильні',
      'mixed_pl': 'Змішані',
      'no_verbs': 'Немає дієслів для тренування',
      'no_verbs_filter': 'Немає дієслів за обраними фільтрами',
      'repeat': 'Повторити',
      'know': 'Знаю',
      'reset_progress': 'Скинути прогрес',
      'reset_title': 'Скинути прогрес?',
      'reset_text': 'Весь прогрес вивчення буде видалено.',
      'cancel': 'Скасувати',
      'reset': 'Скинути',
      'learned_count': '{learned} / {total} дієслів вивчено',
      'learned_by_level': 'Вивчено за рівнями',
      'dark_theme': 'Темна тема',
      'info_title': 'Інформація',
      'info_desc': 'Додаток для вивчення німецьких дієслів з картками та прогресом.',
      'author': 'Автор',
      'author_name': 'Дронов Дмитро',
      'author_desc': 'Розробник та ентузіаст німецької мови. Якщо у вас є питання або пропозиції, відвідайте сайт автора.',
      'website': 'Сайт автора',
      'github_profile': 'GitHub профіль',
      'link': 'Посилання',
      'language': 'Мова',
      'russian': 'Русский',
      'ukrainian': 'Українська',
      'update_available': 'Доступне оновлення',
      'new_version': 'Нова версія:',
      'later': 'Пізніше',
      'update_now': 'Оновити',
      'open_releases': 'Відкрити реліз',
    },
  };
}
