INSERT OR IGNORE INTO verbs (id, infinitive, translation, translation_uk, type, past_participle, preterite, auxiliary_verb, level, example_sentence, example_translation) VALUES
-- A1
(1, 'machen', 'делать', 'робити', 'weak', 'gemacht', 'machte', 'haben', 'A1', 'Ich mache meine Hausaufgaben.', 'Я делаю домашнее задание.'),
(2, 'gehen', 'идти', 'йти', 'strong', 'gegangen', 'ging', 'sein', 'A1', 'Wir gehen heute ins Kino.', 'Мы сегодня идем в кино.'),
(3, 'sagen', 'сказать', 'сказати', 'weak', 'gesagt', 'sagte', 'haben', 'A1', 'Er sagt die Wahrheit.', 'Он говорит правду.'),
(4, 'sehen', 'видеть', 'бачити', 'strong', 'gesehen', 'sah', 'haben', 'A1', 'Sie sieht den Zug.', 'Она видит поезд.'),
(5, 'sein', 'быть', 'бути', 'strong', 'gewesen', 'war', 'sein', 'A1', 'Das ist ein Buch.', 'Это книга.'),
(6, 'haben', 'иметь', 'мати', 'strong', 'gehabt', 'hatte', 'haben', 'A1', 'Ich habe einen Hund.', 'У меня есть собака.'),
(7, 'werden', 'становиться', 'ставати', 'strong', 'geworden', 'wurde', 'sein', 'A1', 'Es wird kalt.', 'Становится холодно.'),
(8, 'geben', 'давать', 'давати', 'strong', 'gegeben', 'gab', 'haben', 'A1', 'Kannst du mir das Buch geben?', 'Ты можешь дать мне книгу?'),
(9, 'kommen', 'приходить', 'приходити', 'strong', 'gekommen', 'kam', 'sein', 'A1', 'Kommst du aus Deutschland?', 'Ты из Германии?'),
(10, 'nehmen', 'брать', 'брати', 'strong', 'genommen', 'nahm', 'haben', 'A1', 'Nimmst du den Bus?', 'Ты берешь автобус?'),
(11, 'finden', 'находить', 'знаходити', 'strong', 'gefunden', 'fand', 'haben', 'A1', 'Ich finde meine Schlüssel nicht.', 'Я не нахожу свои ключи.'),
(12, 'sprechen', 'говорить', 'говорити', 'strong', 'gesprochen', 'sprach', 'haben', 'A1', 'Sprichst du Deutsch?', 'Ты говоришь по-немецки?'),
(13, 'fahren', 'ехать', 'їхати', 'strong', 'gefahren', 'fuhr', 'sein', 'A1', 'Wir fahren nach Berlin.', 'Мы едем в Берлин.'),
(14, 'essen', 'есть', 'їсти', 'strong', 'gegessen', 'aß', 'haben', 'A1', 'Isst du gern Pizza?', 'Ты любишь есть пиццу?'),
(15, 'trinken', 'пить', 'пити', 'strong', 'getrunken', 'trank', 'haben', 'A1', 'Ich trinke Kaffee.', 'Я пью кофе.'),
(16, 'schlafen', 'спать', 'спати', 'strong', 'geschlafen', 'schlief', 'haben', 'A1', 'Das Kind schläft schon.', 'Ребенок уже спит.'),
(17, 'schreiben', 'писать', 'писати', 'strong', 'geschrieben', 'schrieb', 'haben', 'A1', 'Ich schreibe einen Brief.', 'Я пишу письмо.'),
(18, 'lesen', 'читать', 'читати', 'strong', 'gelesen', 'las', 'haben', 'A1', 'Ich lese gern Bücher.', 'Я люблю читать книги.'),
(19, 'arbeiten', 'работать', 'працювати', 'weak', 'gearbeitet', 'arbeitete', 'haben', 'A1', 'Er arbeitet in einer Firma.', 'Он работает в фирме.'),
(20, 'heißen', 'называться', 'називатися', 'weak', 'geheißen', 'hieß', 'haben', 'A1', 'Wie heißt du?', 'Как тебя зовут?'),
(21, 'wohnen', 'жить', 'жити', 'weak', 'gewohnt', 'wohnte', 'haben', 'A1', 'Ich wohne in Berlin.', 'Я живу в Берлине.'),
(22, 'kaufen', 'покупать', 'купувати', 'weak', 'gekauft', 'kaufte', 'haben', 'A1', 'Ich kaufe Brot im Supermarkt.', 'Я покупаю хлеб в супермаркете.'),
(23, 'spielen', 'играть', 'грати', 'weak', 'gespielt', 'spielte', 'haben', 'A1', 'Die Kinder spielen im Park.', 'Дети играют в парке.'),
(24, 'lernen', 'учить', 'вчити', 'weak', 'gelernt', 'lernte', 'haben', 'A1', 'Ich lerne Deutsch.', 'Я учу немецкий.'),
(25, 'können', 'мочь', 'могти', 'mixed', 'gekonnt', 'konnte', 'haben', 'A1', 'Ich kann gut schwimmen.', 'Я хорошо умею плавать.'),
(26, 'müssen', 'должен', 'мусити', 'mixed', 'gemusst', 'musste', 'haben', 'A1', 'Ich muss jetzt gehen.', 'Я должен сейчас идти.'),
(27, 'wollen', 'хотеть', 'хотіти', 'mixed', 'gewollt', 'wollte', 'haben', 'A1', 'Ich will Deutsch lernen.', 'Я хочу учить немецкий.'),
(28, 'wissen', 'знать', 'знати', 'mixed', 'gewusst', 'wusste', 'haben', 'A1', 'Ich weiß die Antwort.', 'Я знаю ответ.'),
(29, 'bringen', 'приносить', 'приносити', 'mixed', 'gebracht', 'brachte', 'haben', 'A1', 'Bringst du mir Wasser?', 'Ты принесешь мне воды?'),
(30, 'suchen', 'искать', 'шукати', 'weak', 'gesucht', 'suchte', 'haben', 'A1', 'Ich suche meine Brille.', 'Я ищу свои очки.'),
(31, 'zeigen', 'показывать', 'показувати', 'weak', 'gezeigt', 'zeigte', 'haben', 'A1', 'Zeig mir den Weg!', 'Покажи мне дорогу!'),
(32, 'fragen', 'спрашивать', 'питати', 'weak', 'gefragt', 'fragte', 'haben', 'A1', 'Er fragt nach dem Preis.', 'Он спрашивает о цене.'),
(33, 'antworten', 'отвечать', 'відповідати', 'weak', 'geantwortet', 'antwortete', 'haben', 'A1', 'Sie antwortet auf die Frage.', 'Она отвечает на вопрос.'),
(34, 'öffnen', 'открывать', 'відкривати', 'weak', 'geöffnet', 'öffnete', 'haben', 'A1', 'Öffne bitte das Fenster!', 'Открой, пожалуйста, окно!'),
(35, 'schließen', 'закрывать', 'закривати', 'strong', 'geschlossen', 'schloss', 'haben', 'A1', 'Schließ bitte die Tür!', 'Закрой, пожалуйста, дверь!'),
(36, 'reisen', 'путешествовать', 'подорожувати', 'weak', 'gereist', 'reiste', 'sein', 'A1', 'Ich reise gern nach Italien.', 'Я люблю путешествовать в Италию.'),
(37, 'tanzen', 'танцевать', 'танцювати', 'weak', 'getanzt', 'tanzte', 'haben', 'A1', 'Sie tanzt sehr gut.', 'Она очень хорошо танцует.'),
(38, 'singen', 'петь', 'співати', 'strong', 'gesungen', 'sang', 'haben', 'A1', 'Wir singen ein Lied.', 'Мы поем песню.'),
(39, 'lachen', 'смеяться', 'сміятися', 'weak', 'gelacht', 'lachte', 'haben', 'A1', 'Die Kinder lachen laut.', 'Дети громко смеются.'),
(40, 'weinen', 'плакать', 'плакати', 'weak', 'geweint', 'weinte', 'haben', 'A1', 'Das Baby weint.', 'Ребенок плачет.'),
(41, 'helfen', 'помогать', 'допомагати', 'strong', 'geholfen', 'half', 'haben', 'A1', 'Kann ich dir helfen?', 'Я могу тебе помочь?'),
(42, 'danken', 'благодарить', 'дякувати', 'weak', 'gedankt', 'dankte', 'haben', 'A1', 'Ich danke dir herzlich.', 'Я сердечно благодарю тебя.'),
(43, 'kochen', 'готовить', 'готувати', 'weak', 'gekocht', 'kochte', 'haben', 'A1', 'Sie kocht heute Abend.', 'Она готовит сегодня вечером.'),
(44, 'träumen', 'мечтать', 'мріяти', 'weak', 'geträumt', 'träumte', 'haben', 'A1', 'Ich träume von einer Reise.', 'Я мечтаю о путешествии.'),
(45, 'lieben', 'любить', '', 'weak', 'geliebt', 'liebte', 'haben', 'A1', 'Ich liebe dich.', 'Я люблю тебя.'),
(46, 'dürfen', 'мочь (разрешение)', 'могти (дозвіл)', 'mixed', 'gedurft', 'durfte', 'haben', 'A1', 'Darf ich hier parken?', 'Мне можно здесь парковаться?'),
(47, 'sollen', 'быть должным', 'бути повинним', 'mixed', 'gesollt', 'sollte', 'haben', 'A1', 'Soll ich das Fenster öffnen?', 'Мне открыть окно?'),
-- A2
(48, 'verstehen', 'понимать', 'розуміти', 'strong', 'verstanden', 'verstand', 'haben', 'A2', 'Verstehst du die Frage?', 'Ты понимаешь вопрос?'),
(49, 'denken', 'думать', 'думати', 'mixed', 'gedacht', 'dachte', 'haben', 'A2', 'Was denkst du darüber?', 'Что ты об этом думаешь?'),
(50, 'vergessen', 'забывать', 'забувати', 'strong', 'vergessen', 'vergaß', 'haben', 'A2', 'Ich habe meinen Schlüssel vergessen.', 'Я забыл свой ключ.'),
(51, 'treffen', 'встречать', 'зустрічати', 'strong', 'getroffen', 'traf', 'haben', 'A2', 'Ich treffe meine Freunde.', 'Я встречаю своих друзей.'),
(52, 'laufen', 'бежать', 'бігти', 'strong', 'gelaufen', 'lief', 'sein', 'A2', 'Er läuft jeden Morgen.', 'Он бегает каждое утро.'),
(53, 'lassen', 'позволять', 'дозволяти', 'strong', 'gelassen', 'ließ', 'haben', 'A2', 'Lass mich in Ruhe!', 'Оставь меня в покое!'),
(54, 'halten', 'держать', 'тримати', 'strong', 'gehalten', 'hielt', 'haben', 'A2', 'Kannst du das bitte halten?', 'Ты можешь это подержать?'),
(55, 'ziehen', 'тянуть', 'тягнути', 'strong', 'gezogen', 'zog', 'haben', 'A2', 'Der Hund zieht an der Leine.', 'Собака тянет поводок.'),
(56, 'tragen', 'носить', '', 'strong', 'getragen', 'trug', 'haben', 'A2', 'Sie trägt ein Kleid.', 'Она носит платье.'),
(57, 'fallen', 'падать', 'падати', 'strong', 'gefallen', 'fiel', 'sein', 'A2', 'Das Blatt fällt vom Baum.', 'Лист падает с дерева.'),
(58, 'fangen', 'ловить', 'ловити', 'strong', 'gefangen', 'fing', 'haben', 'A2', 'Die Katze fängt eine Maus.', 'Кошка ловит мышь.'),
(59, 'hängen', 'висеть', 'висіти', 'strong', 'gehangen', 'hing', 'haben', 'A2', 'Das Bild hängt an der Wand.', 'Картина висит на стене.'),
(60, 'werfen', 'бросать', 'кидати', 'strong', 'geworfen', 'warf', 'haben', 'A2', 'Wirf den Ball!', 'Брось мяч!'),
(61, 'steigen', 'подниматься', 'підніматися', 'strong', 'gestiegen', 'stieg', 'sein', 'A2', 'Die Preise steigen.', 'Цены растут.'),
(62, 'fliegen', 'летать', 'літати', 'strong', 'geflogen', 'flog', 'sein', 'A2', 'Wir fliegen nach Spanien.', 'Мы летим в Испанию.'),
(63, 'schwimmen', 'плавать', 'плавати', 'strong', 'geschwommen', 'schwamm', 'sein', 'A2', 'Er schwimmt im See.', 'Он плавает в озере.'),
(64, 'springen', 'прыгать', 'стрибати', 'strong', 'gesprungen', 'sprang', 'sein', 'A2', 'Das Kind springt ins Wasser.', 'Ребенок прыгает в воду.'),
(65, 'sitzen', 'сидеть', 'сидіти', 'strong', 'gesessen', 'saß', 'haben', 'A2', 'Wir sitzen im Park.', 'Мы сидим в парке.'),
(66, 'stehen', 'стоять', 'стояти', 'strong', 'gestanden', 'stand', 'haben', 'A2', 'Das Glas steht auf dem Regal.', 'Стакан стоит на полке.'),
(67, 'liegen', 'лежать', 'лежати', 'strong', 'gelegen', 'lag', 'haben', 'A2', 'Das Buch liegt auf dem Tisch.', 'Книга лежит на столе.'),
(68, 'tun', 'делать', 'робити', 'strong', 'getan', 'tat', 'haben', 'A2', 'Was tust du da?', 'Что ты там делаешь?'),
(69, 'waschen', 'мыть', '', 'strong', 'gewaschen', 'wusch', 'haben', 'A2', 'Ich wasche meine Hände.', 'Я мою руки.'),
(70, 'anrufen', 'звонить', '', 'strong', 'angerufen', 'rief an', 'haben', 'A2', 'Ich rufe dich morgen an.', 'Я позвоню тебе завтра.'),
(71, 'einladen', 'приглашать', '', 'strong', 'eingeladen', 'lud ein', 'haben', 'A2', 'Er lädt mich zur Party ein.', 'Он приглашает меня на вечеринку.'),
(72, 'bezahlen', 'платить', '', 'weak', 'bezahlt', 'bezahlte', 'haben', 'A2', 'Ich bezahle die Rechnung.', 'Я оплачиваю счет.'),
(73, 'erklären', 'объяснять', '', 'weak', 'erklärt', 'erklärte', 'haben', 'A2', 'Kannst du das erklären?', 'Ты можешь это объяснить?'),
(74, 'erzählen', 'рассказывать', '', 'weak', 'erzählt', 'erzählte', 'haben', 'A2', 'Er erzählt eine Geschichte.', 'Он рассказывает историю.'),
(75, 'folgen', 'следовать', '', 'weak', 'gefolgt', 'folgte', 'sein', 'A2', 'Folge mir!', 'Следуй за мной!'),
(76, 'interessieren', 'интересовать', '', 'weak', 'interessiert', 'interessierte', 'haben', 'A2', 'Das interessiert mich sehr.', 'Это меня очень интересует.'),
(77, 'passieren', 'случаться', '', 'weak', 'passiert', 'passierte', 'sein', 'A2', 'Was ist passiert?', 'Что случилось?'),
(78, 'schicken', 'посылать', '', 'weak', 'geschickt', 'schickte', 'haben', 'A2', 'Ich schicke dir eine Nachricht.', 'Я отправляю тебе сообщение.'),
(79, 'schmecken', 'быть вкусным', '', 'weak', 'geschmeckt', 'schmeckte', 'haben', 'A2', 'Das Essen schmeckt gut.', 'Еда вкусная.'),
(80, 'wünschen', 'желать', '', 'weak', 'gewünscht', 'wünschte', 'haben', 'A2', 'Ich wünsche dir alles Gute!', 'Я желаю тебе всего хорошего!'),
(81, 'wiederholen', 'повторять', '', 'weak', 'wiederholt', 'wiederholte', 'haben', 'A2', 'Wiederhole bitte den Satz.', 'Повтори, пожалуйста, предложение.'),
(82, 'zeichnen', 'рисовать', '', 'weak', 'gezeichnet', 'zeichnete', 'haben', 'A2', 'Das Kind zeichnet ein Bild.', 'Ребенок рисует картинку.'),
(83, 'putzen', 'чистить', '', 'weak', 'geputzt', 'putzte', 'haben', 'A2', 'Ich putze meine Zähne.', 'Я чищу зубы.'),
(84, 'rechnen', 'считать', '', 'weak', 'gerechnet', 'rechnete', 'haben', 'A2', 'Er rechnet schnell.', 'Он быстро считает.'),
(85, 'bedeuten', 'означать', '', 'weak', 'bedeutet', 'bedeutete', 'haben', 'A2', 'Was bedeutet dieses Wort?', 'Что означает это слово?'),
(86, 'beginnen', 'начинать', '', 'strong', 'begonnen', 'begann', 'haben', 'A2', 'Der Unterricht beginnt um neun.', 'Урок начинается в девять.'),
(87, 'bekommen', 'получать', '', 'strong', 'bekommen', 'bekam', 'haben', 'A2', 'Ich bekomme ein Geschenk.', 'Я получаю подарок.'),
-- B1
(88, 'legen', 'класть', 'класти', 'weak', 'gelegt', 'legte', 'haben', 'B1', 'Ich lege das Buch auf den Tisch.', 'Я кладу книгу на стол.'),
(89, 'stellen', 'ставить', 'ставити', 'weak', 'gestellt', 'stellte', 'haben', 'B1', 'Stell die Tassen auf den Tisch!', 'Поставь чашки на стол!'),
(90, 'setzen', 'сажать', 'садити', 'weak', 'gesetzt', 'setzte', 'haben', 'B1', 'Sie setzt das Kind auf den Stuhl.', 'Она сажает ребенка на стул.'),
(91, 'drücken', 'давить', 'тиснути', 'weak', 'gedrückt', 'drückte', 'haben', 'B1', 'Drücke die Taste!', 'Нажми на кнопку!'),
(92, 'biegen', 'гнуть', 'гнути', 'strong', 'gebogen', 'bog', 'haben', 'B1', 'Der Ast biegt sich im Wind.', 'Ветка гнется на ветру.'),
(93, 'brechen', 'ломать', 'ламати', 'strong', 'gebrochen', 'brach', 'haben', 'B1', 'Das Glas ist gebrochen.', 'Стакан разбился.'),
(94, 'erfinden', 'изобретать', 'винаходити', 'strong', 'erfunden', 'erfand', 'haben', 'B1', 'Wer hat das erfunden?', 'Кто это изобрел?'),
(95, 'erlauben', 'разрешать', 'дозволяти', 'weak', 'erlaubt', 'erlaubte', 'haben', 'B1', 'Die Eltern erlauben es.', 'Родители это разрешают.'),
(96, 'erscheinen', 'появляться', 'з''являтися', 'strong', 'erschienen', 'erschien', 'sein', 'B1', 'Die Sonne erscheint am Horizont.', 'Солнце появляется на горизонте.'),
(97, 'fliehen', 'убегать', 'тікати', 'strong', 'geflohen', 'floh', 'sein', 'B1', 'Der Täter flieht vom Tatort.', 'Преступник убегает с места преступления.'),
(98, 'fließen', 'течь', 'текти', 'strong', 'geflossen', 'floss', 'sein', 'B1', 'Der Fluss fließt ins Meer.', 'Река впадает в море.'),
(99, 'frieren', 'мерзнуть', 'мерзнути', 'strong', 'gefroren', 'fror', 'haben', 'B1', 'Ich friere im Winter.', 'Я мерзну зимой.'),
(100, 'genießen', 'наслаждаться', 'насолоджуватися', 'strong', 'genossen', 'genoss', 'haben', 'B1', 'Ich genieße das gute Wetter.', 'Я наслаждаюсь хорошей погодой.'),
(101, 'gewinnen', 'выигрывать', 'вигравати', 'strong', 'gewonnen', 'gewann', 'haben', 'B1', 'Wir haben das Spiel gewonnen.', 'Мы выиграли игру.'),
(102, 'greifen', 'хватать', 'хапати', 'strong', 'gegriffen', 'griff', 'haben', 'B1', 'Er greift nach dem Glas.', 'Он хватается за стакан.'),
(103, 'kriechen', 'ползти', 'повзти', 'strong', 'gekrochen', 'kroch', 'sein', 'B1', 'Das Baby kriecht auf dem Boden.', 'Ребенок ползает по полу.'),
(104, 'leiden', 'страдать', 'страждати', 'strong', 'gelitten', 'litt', 'haben', 'B1', 'Er leidet unter Schmerzen.', 'Он страдает от боли.'),
(105, 'leihen', 'одалживать', 'позичати', 'strong', 'geliehen', 'lieh', 'haben', 'B1', 'Kannst du mir Geld leihen?', 'Ты можешь одолжить мне деньги?'),
(106, 'lügen', 'лгать', 'брехати', 'strong', 'gelogen', 'log', 'haben', 'B1', 'Er lügt nie.', 'Он никогда не лжет.'),
(107, 'messen', 'измерять', 'вимірювати', 'strong', 'gemessen', 'maß', 'haben', 'B1', 'Der Arzt misst den Blutdruck.', 'Врач измеряет давление.'),
(108, 'raten', 'советовать', 'радити', 'strong', 'geraten', 'riet', 'haben', 'B1', 'Was rätst du mir?', 'Что ты мне советуешь?'),
(109, 'reißen', 'рвать', 'рвати', 'strong', 'gerissen', 'riss', 'haben', 'B1', 'Das Papier reißt leicht.', 'Бумага легко рвется.'),
(110, 'riechen', 'нюхать', 'нюхати', 'strong', 'gerochen', 'roch', 'haben', 'B1', 'Die Blume riecht gut.', 'Цветок хорошо пахнет.'),
(111, 'rufen', 'кричать', 'кричати', 'strong', 'gerufen', 'rief', 'haben', 'B1', 'Er ruft nach Hilfe.', 'Он зовет на помощь.'),
(112, 'schieben', 'толкать', 'штовхати', 'strong', 'geschoben', 'schob', 'haben', 'B1', 'Schieb den Tisch zur Seite!', 'Отодвинь стол в сторону!'),
(113, 'schießen', 'стрелять', 'стріляти', 'strong', 'geschossen', 'schoss', 'haben', 'B1', 'Der Jäger schießt nicht.', 'Охотник не стреляет.'),
(114, 'schlagen', 'бить', 'бити', 'strong', 'geschlagen', 'schlug', 'haben', 'B1', 'Das Herz schlägt schnell.', 'Сердце бьется быстро.'),
(115, 'schneiden', 'резать', 'різати', 'strong', 'geschnitten', 'schnitt', 'haben', 'B1', 'Schneide das Brot in Scheiben.', 'Нарежь хлеб ломтиками.'),
(116, 'schreien', 'кричать', 'кричати', 'strong', 'geschrien', 'schrie', 'haben', 'B1', 'Die Kinder schreien vor Freude.', 'Дети кричат от радости.'),
(117, 'schweigen', 'молчать', 'мовчати', 'strong', 'geschwiegen', 'schwieg', 'haben', 'B1', 'Er schweigt die ganze Zeit.', 'Он молчит все время.'),
(118, 'schwingen', 'качать', 'гойдати', 'strong', 'geschwungen', 'schwang', 'haben', 'B1', 'Die Tür schwingt im Wind.', 'Дверь качается на ветру.'),
(119, 'sinken', 'тонуть', 'тонути', 'strong', 'gesunken', 'sank', 'sein', 'B1', 'Das Schiff sinkt langsam.', 'Корабль медленно тонет.'),
(120, 'spinnen', 'прясть', 'прясти', 'strong', 'gesponnen', 'spann', 'haben', 'B1', 'Die Spinne spinnt ein Netz.', 'Паук плетет паутину.'),
(121, 'stechen', 'колоть', 'колоти', 'strong', 'gestochen', 'stach', 'haben', 'B1', 'Die Biene sticht.', 'Пчела жалит.'),
(122, 'stehlen', 'воровать', 'красти', 'strong', 'gestohlen', 'stahl', 'haben', 'B1', 'Jemand hat mein Fahrrad gestohlen.', 'Кто-то украл мой велосипед.'),
(123, 'sterben', 'умирать', 'вмирати', 'strong', 'gestorben', 'starb', 'sein', 'B1', 'Die Blume stirbt ohne Wasser.', 'Цветок умирает без воды.'),
(124, 'stoßen', 'толкать', 'штовхати', 'strong', 'gestoßen', 'stieß', 'haben', 'B1', 'Er stößt gegen die Tür.', 'Он ударяется о дверь.'),
(125, 'streichen', 'красить', '', 'strong', 'gestrichen', 'strich', 'haben', 'B1', 'Wir streichen die Wand weiß.', 'Мы красим стену в белый.'),
(126, 'streiten', 'ссориться', 'сваритися', 'strong', 'gestritten', 'stritt', 'haben', 'B1', 'Die Kinder streiten sich.', 'Дети ссорятся.'),
(127, 'treiben', 'гнать', 'гнати', 'strong', 'getrieben', 'trieb', 'haben', 'B1', 'Der Wind treibt die Wolken.', 'Ветер гонит облака.'),
(128, 'treten', 'ступать', 'ступати', 'strong', 'getreten', 'trat', 'sein', 'B1', 'Tritt nicht auf die Blumen!', 'Не наступай на цветы!'),
(129, 'verderben', 'портить', 'псувати', 'strong', 'verdorben', 'verdarb', 'haben', 'B1', 'Die Hitze verdirbt das Essen.', 'Жара портит еду.'),
(130, 'verlieren', 'терять', 'губити', 'strong', 'verloren', 'verlor', 'haben', 'B1', 'Ich habe meine Brieftasche verloren.', 'Я потерял свой бумажник.'),
(131, 'verzeihen', 'прощать', 'прощати', 'strong', 'verziehen', 'verzieh', 'haben', 'B1', 'Verzeih mir bitte!', 'Прости меня, пожалуйста!'),
(132, 'wachsen', 'расти', 'рости', 'strong', 'gewachsen', 'wuchs', 'sein', 'B1', 'Die Pflanze wächst schnell.', 'Растение быстро растет.'),
(133, 'wiegen', 'взвешивать', 'зважувати', 'strong', 'gewogen', 'wog', 'haben', 'B1', 'Sie wiegt das Mehl.', 'Она взвешивает муку.'),
(134, 'zwingen', 'заставлять', 'змушувати', 'strong', 'gezwungen', 'zwang', 'haben', 'B1', 'Niemand zwingt dich.', 'Никто тебя не заставляет.'),
(135, 'vorbereiten', 'готовить', 'готувати', 'weak', 'vorbereitet', 'bereitete vor', 'haben', 'B1', 'Ich bereite mich auf die Prüfung vor.', 'Я готовлюсь к экзамену.'),
(136, 'verdienen', 'зарабатывать', 'заробляти', 'weak', 'verdient', 'verdiente', 'haben', 'B1', 'Er verdient gut.', 'Он хорошо зарабатывает.'),
(137, 'verbringen', 'проводить', 'проводити', 'strong', 'verbracht', 'verbrachte', 'haben', 'B1', 'Wir verbringen den Urlaub am Meer.', 'Мы проводим отпуск у моря.'),
(138, 'versuchen', 'пытаться', 'намагатися', 'weak', 'versucht', 'versuchte', 'haben', 'B1', 'Ich versuche mein Bestes.', 'Я стараюсь изо всех сил.'),
(139, 'vorstellen', 'представлять', 'представляти', 'weak', 'vorgestellt', 'stellte vor', 'haben', 'B1', 'Darf ich mich vorstellen?', 'Разрешите представиться?'),
(140, 'bestehen', 'состоять', 'складатися', 'strong', 'bestanden', 'bestand', 'haben', 'B1', 'Die Prüfung besteht aus drei Teilen.', 'Экзамен состоит из трех частей.'),
(141, 'betrachten', 'рассматривать', 'розглядати', 'weak', 'betrachtet', 'betrachtete', 'haben', 'B1', 'Er betrachtet das Bild genau.', 'Он внимательно рассматривает картину.'),
(142, 'bewegen', 'двигать', 'рухати', 'weak', 'bewegt', 'bewegte', 'haben', 'B1', 'Beweg dich nicht!', 'Не двигайся!'),
(143, 'einkaufen', 'покупать', 'купувати', 'weak', 'eingekauft', 'kaufte ein', 'haben', 'B1', 'Ich kaufe morgen ein.', 'Я иду за покупками завтра.'),
(144, 'entscheiden', 'решать', 'вирішувати', 'strong', 'entschieden', 'entschied', 'haben', 'B1', 'Ich muss mich schnell entscheiden.', 'Я должен быстро решиться.'),
(145, 'empfangen', 'принимать', 'приймати', 'strong', 'empfangen', 'empfing', 'haben', 'B1', 'Wir empfangen Gäste.', 'Мы принимаем гостей.'),
(146, 'empfehlen', 'рекомендовать', 'рекомендувати', 'strong', 'empfohlen', 'empfahl', 'haben', 'B1', 'Ich empfehle dieses Restaurant.', 'Я рекомендую этот ресторан.'),
(147, 'entdecken', 'обнаруживать', 'виявляти', 'weak', 'entdeckt', 'entdeckte', 'haben', 'B1', 'Kolumbus entdeckte Amerika.', 'Колумб открыл Америку.'),
(148, 'enthalten', 'содержать', 'містити', 'strong', 'enthalten', 'enthielt', 'haben', 'B1', 'Die Flasche enthält Wasser.', 'Бутылка содержит воду.'),
(149, 'entwickeln', 'развивать', 'розвивати', 'weak', 'entwickelt', 'entwickelte', 'haben', 'B1', 'Das Unternehmen entwickelt neue Produkte.', 'Компания разрабатывает новые продукты.'),
(150, 'erreichen', 'достигать', 'досягати', 'weak', 'erreicht', 'erreichte', 'haben', 'B1', 'Wir erreichen das Ziel.', 'Мы достигаем цели.'),
-- B2
(151, 'beschreiben', 'описывать', 'описувати', 'strong', 'beschrieben', 'beschrieb', 'haben', 'B2', 'Kannst du den Weg beschreiben?', 'Ты можешь описать дорогу?'),
(152, 'bieten', 'предлагать', 'пропонувати', 'strong', 'geboten', 'bot', 'haben', 'B2', 'Die Firma bietet gute Leistungen.', 'Фирма предлагает хорошие услуги.'),
(153, 'genesen', 'выздоравливать', 'одужувати', 'strong', 'genesen', 'genas', 'sein', 'B2', 'Der Patient genest langsam.', 'Пациент медленно выздоравливает.'),
(154, 'unternehmen', 'предпринимать', 'здійснювати', 'strong', 'unternommen', 'unternahm', 'haben', 'B2', 'Was möchtest du heute unternehmen?', 'Что ты хочешь предпринять сегодня?'),
(155, 'ausschließen', 'исключать', 'виключати', 'strong', 'ausgeschlossen', 'schloss aus', 'haben', 'B2', 'Ich schließe das nicht aus.', 'Я этого не исключаю.'),
(156, 'behandeln', 'обрабатывать', 'обробляти', 'weak', 'behandelt', 'behandelte', 'haben', 'B2', 'Der Arzt behandelt den Patienten.', 'Врач лечит пациента.'),
(157, 'beschäftigen', 'занимать', 'займати', 'weak', 'beschäftigt', 'beschäftigte', 'haben', 'B2', 'Womit beschäftigst du dich?', 'Чем ты занимаешься?'),
(158, 'betreiben', 'заниматься', 'займатися', 'strong', 'betrieben', 'betrieb', 'haben', 'B2', 'Er betreibt ein Geschäft.', 'Он управляет магазином.'),
(159, 'beurteilen', 'оценивать', 'оцінювати', 'weak', 'beurteilt', 'beurteilte', 'haben', 'B2', 'Ich beurteile die Lage.', 'Я оцениваю ситуацию.'),
(160, 'bewerben', 'подавать заявку', 'подавати заявку', 'strong', 'beworben', 'bewarb', 'haben', 'B2', 'Sie bewirbt sich um die Stelle.', 'Она подает заявку на эту должность.'),
(161, 'beziehen', 'ссылаться', 'посилатися', 'strong', 'bezogen', 'bezog', 'haben', 'B2', 'Worauf beziehst du dich?', 'На что ты ссылаешься?'),
(162, 'einrichten', 'устраивать', 'влаштовувати', 'weak', 'eingerichtet', 'richtete ein', 'haben', 'B2', 'Wir richten die Wohnung ein.', 'Мы обставляем квартиру.'),
(163, 'entsprechen', 'соответствовать', 'відповідати', 'strong', 'entsprochen', 'entsprach', 'haben', 'B2', 'Das entspricht nicht der Wahrheit.', 'Это не соответствует правде.'),
(164, 'entstehen', 'возникать', 'виникати', 'strong', 'entstanden', 'entstand', 'sein', 'B2', 'Aus der Idee entsteht ein Projekt.', 'Из идеи возникает проект.'),
(165, 'erheben', 'поднимать', 'піднімати', 'strong', 'erhoben', 'erhob', 'haben', 'B2', 'Er erhebt sein Glas.', 'Он поднимает свой бокал.'),
(166, 'erkennen', 'узнавать', 'впізнавати', 'mixed', 'erkannt', 'erkannte', 'haben', 'B2', 'Ich erkenne dich nicht wieder.', 'Я тебя не узнаю.'),
(167, 'ernennen', 'назначать', 'призначати', 'mixed', 'ernannt', 'ernannte', 'haben', 'B2', 'Er wird zum Chef ernannt.', 'Его назначают начальником.'),
(168, 'ersetzen', 'заменять', 'замінювати', 'weak', 'ersetzt', 'ersetzte', 'haben', 'B2', 'Kannst du mich ersetzen?', 'Ты можешь меня заменить?'),
(169, 'erwähnen', 'упоминать', 'згадувати', 'weak', 'erwähnt', 'erwähnte', 'haben', 'B2', 'Er erwähnte deinen Namen.', 'Он упомянул твое имя.'),
(170, 'erwarten', 'ожидать', 'очікувати', 'weak', 'erwartet', 'erwartete', 'haben', 'B2', 'Ich erwarte eine Antwort.', 'Я ожидаю ответ.'),
(171, 'erzeugen', 'производить', 'виробляти', 'weak', 'erzeugt', 'erzeugte', 'haben', 'B2', 'Die Maschine erzeugt Strom.', 'Машина производит электричество.'),
(172, 'feststellen', 'устанавливать', 'встановлювати', 'weak', 'festgestellt', 'stellte fest', 'haben', 'B2', 'Der Arzt stellt die Diagnose fest.', 'Врач устанавливает диагноз.'),
(173, 'herstellen', 'производить', 'виробляти', 'weak', 'hergestellt', 'stellte her', 'haben', 'B2', 'Die Firma stellt Möbel her.', 'Фирма производит мебель.'),
(174, 'umgehen', 'обходить', 'обходити', 'strong', 'umgangen', 'umging', 'haben', 'B2', 'Wir müssen das Problem umgehen.', 'Мы должны обойти эту проблему.'),
(175, 'unterbrechen', 'прерывать', 'переривати', 'strong', 'unterbrochen', 'unterbrach', 'haben', 'B2', 'Entschuldigung, ich möchte nicht unterbrechen.', 'Извините, я не хочу прерывать.'),
(176, 'unterhalten', 'развлекать', 'розважати', 'strong', 'unterhalten', 'unterhielt', 'haben', 'B2', 'Wir unterhalten uns über Bücher.', 'Мы беседуем о книгах.'),
(177, 'unterscheiden', 'различать', 'розрізняти', 'strong', 'unterschieden', 'unterschied', 'haben', 'B2', 'Kannst du die Vögel unterscheiden?', 'Ты можешь различить птиц?'),
(178, 'untersuchen', 'исследовать', 'досліджувати', 'weak', 'untersucht', 'untersuchte', 'haben', 'B2', 'Der Arzt untersucht den Patienten.', 'Врач обследует пациента.'),
(179, 'verändern', 'изменять', 'змінювати', 'weak', 'verändert', 'veränderte', 'haben', 'B2', 'Das Leben verändert sich ständig.', 'Жизнь постоянно меняется.'),
(180, 'verbessern', 'улучшать', 'покращувати', 'weak', 'verbessert', 'verbesserte', 'haben', 'B2', 'Ich möchte mein Deutsch verbessern.', 'Я хочу улучшить свой немецкий.'),
(181, 'verbieten', 'запрещать', 'забороняти', 'strong', 'verboten', 'verbot', 'haben', 'B2', 'Rauchen ist hier verboten.', 'Здесь курить запрещено.'),
(182, 'verbinden', 'соединять', 'з''єднувати', 'strong', 'verbunden', 'verband', 'haben', 'B2', 'Diese Straße verbindet zwei Städte.', 'Эта дорога соединяет два города.'),
(183, 'vereinbaren', 'договариваться', 'домовлятися', 'weak', 'vereinbart', 'vereinbarte', 'haben', 'B2', 'Wir vereinbaren einen Termin.', 'Мы договариваемся о встрече.'),
(184, 'verfolgen', 'преследовать', 'переслідувати', 'weak', 'verfolgt', 'verfolgte', 'haben', 'B2', 'Die Polizei verfolgt den Täter.', 'Полиция преследует преступника.'),
(185, 'verfügen', 'распоряжаться', 'розпоряджатися', 'weak', 'verfügt', 'verfügte', 'haben', 'B2', 'Er verfügt über viel Erfahrung.', 'Он обладает большим опытом.'),
(186, 'vergleichen', 'сравнивать', 'порівнювати', 'strong', 'verglichen', 'verglich', 'haben', 'B2', 'Vergleiche die beiden Texte!', 'Сравни оба текста!'),
(187, 'verhandeln', 'вести переговоры', 'вести переговори', 'weak', 'verhandelt', 'verhandelte', 'haben', 'B2', 'Sie verhandeln über den Preis.', 'Они ведут переговоры о цене.'),
(188, 'verkaufen', 'продавать', 'продавати', 'weak', 'verkauft', 'verkaufte', 'haben', 'B2', 'Das Haus wurde verkauft.', 'Дом был продан.'),
(189, 'verlangen', 'требовать', 'вимагати', 'weak', 'verlangt', 'verlangte', 'haben', 'B2', 'Ich verlange eine Erklärung.', 'Я требую объяснения.'),
(190, 'vermeiden', 'избегать', 'уникати', 'strong', 'vermieden', 'vermied', 'haben', 'B2', 'Vermeide unnötige Risiken!', 'Избегай ненужных рисков!'),
(191, 'veröffentlichen', 'публиковать', 'публікувати', 'weak', 'veröffentlicht', 'veröffentlichte', 'haben', 'B2', 'Der Artikel wurde veröffentlicht.', 'Статья была опубликована.'),
(192, 'verschieben', 'откладывать', 'відкладати', 'strong', 'verschoben', 'verschob', 'haben', 'B2', 'Wir verschieben das Treffen.', 'Мы переносим встречу.'),
(193, 'versichern', 'страховать', 'страхувати', 'weak', 'versichert', 'versicherte', 'haben', 'B2', 'Ich versichere mein Auto.', 'Я страхую свою машину.'),
(194, 'versorgen', 'снабжать', 'постачати', 'weak', 'versorgt', 'versorgte', 'haben', 'B2', 'Die Familie ist gut versorgt.', 'Семья хорошо обеспечена.'),
(195, 'verteilen', 'распределять', 'розподіляти', 'weak', 'verteilt', 'verteilte', 'haben', 'B2', 'Der Lehrer verteilt die Blätter.', 'Учитель раздает листы.'),
(196, 'vertrauen', 'доверять', 'довіряти', 'weak', 'vertraut', 'vertraute', 'haben', 'B2', 'Ich vertraue dir.', 'Я тебе доверяю.'),
(197, 'verwalten', 'управлять', 'керувати', 'weak', 'verwaltet', 'verwaltete', 'haben', 'B2', 'Er verwaltet das Vermögen.', 'Он управляет имуществом.'),
(198, 'verwenden', 'использовать', 'використовувати', 'weak', 'verwendet', 'verwendete', 'haben', 'B2', 'Welches Wort verwendet man hier?', 'Какое слово здесь используется?'),
(199, 'verzichten', 'отказываться', 'відмовлятися', 'weak', 'verzichtet', 'verzichtete', 'haben', 'B2', 'Ich verzichte auf Zucker.', 'Я отказываюсь от сахара.'),
(200, 'vorwerfen', 'упрекать', 'дорікати', 'strong', 'vorgeworfen', 'warf vor', 'haben', 'B2', 'Was wirfst du mir vor?', 'В чем ты меня упрекаешь?'),
(201, 'widersprechen', 'возражать', 'заперечувати', 'strong', 'widersprochen', 'widersprach', 'haben', 'B2', 'Ich widerspreche dir nicht.', 'Я тебе не возражаю.'),
(202, 'zubereiten', 'готовить', 'готувати', 'weak', 'zubereitet', 'bereitete zu', 'haben', 'B2', 'Sie bereitet das Abendessen zu.', 'Она готовит ужин.'),
(203, 'zusammenfassen', 'резюмировать', 'узагальнювати', 'weak', 'zusammengefasst', 'fasste zusammen', 'haben', 'B2', 'Fassen Sie den Text zusammen!', 'Обобщите текст!'),
-- C1
(204, 'abschließen', 'завершать', 'завершувати', 'strong', 'abgeschlossen', 'schloss ab', 'haben', 'C1', 'Wir schließen das Projekt ab.', 'Мы завершаем проект.'),
(205, 'anerkennen', 'признавать', 'визнавати', 'mixed', 'anerkannt', 'erkannte an', 'haben', 'C1', 'Seine Leistung wurde anerkannt.', 'Его достижение было признано.'),
(206, 'anpassen', 'приспосабливать', 'пристосовувати', 'weak', 'angepasst', 'passte an', 'haben', 'C1', 'Man muss sich den Regeln anpassen.', 'Нужно приспосабливаться к правилам.'),
(207, 'aufweisen', 'показывать', 'показувати', 'strong', 'aufgewiesen', 'wies auf', 'haben', 'C1', 'Das Gerät weist Mängel auf.', 'Прибор показывает недостатки.'),
(208, 'ausüben', 'осуществлять', 'здійснювати', 'weak', 'ausgeübt', 'übte aus', 'haben', 'C1', 'Er übt seinen Beruf mit Leidenschaft aus.', 'Он занимается своей профессией со страстью.'),
(209, 'beeinflussen', 'влиять', 'впливати', 'weak', 'beeinflusst', 'beeinflusste', 'haben', 'C1', 'Die Medien beeinflussen die Meinung.', 'СМИ влияют на мнение.'),
(210, 'befinden', 'находиться', 'знаходитися', 'strong', 'befunden', 'befand', 'haben', 'C1', 'Das Museum befindet sich im Zentrum.', 'Музей находится в центре.'),
(211, 'begleiten', 'сопровождать', 'супроводжувати', 'weak', 'begleitet', 'begleitete', 'haben', 'C1', 'Ich begleite dich nach Hause.', 'Я провожу тебя домой.'),
(212, 'bekämpfen', 'бороться', 'боротися', 'weak', 'bekämpft', 'bekämpfte', 'haben', 'C1', 'Wir bekämpfen den Klimawandel.', 'Мы боремся с изменением климата.'),
(213, 'benutzen', 'использовать', 'використовувати', 'weak', 'benutzt', 'benutzte', 'haben', 'C1', 'Darf ich dein Telefon benutzen?', 'Можно воспользоваться твоим телефоном?'),
(214, 'berücksichtigen', 'учитывать', 'враховувати', 'weak', 'berücksichtigt', 'berücksichtigte', 'haben', 'C1', 'Wir müssen alle Faktoren berücksichtigen.', 'Мы должны учесть все факторы.'),
(215, 'beschließen', 'решать', 'вирішувати', 'strong', 'beschlossen', 'beschloss', 'haben', 'C1', 'Der Vorstand beschließt die neue Strategie.', 'Правление утверждает новую стратегию.'),
(216, 'bestätigen', 'подтверждать', 'підтверджувати', 'weak', 'bestätigt', 'bestätigte', 'haben', 'C1', 'Ich bestätige den Empfang.', 'Я подтверждаю получение.'),
(217, 'beteiligen', 'участвовать', 'брати участь', 'weak', 'beteiligt', 'beteiligte', 'haben', 'C1', 'Er beteiligt sich an dem Projekt.', 'Он участвует в проекте.'),
(218, 'betonen', 'подчеркивать', 'підкреслювати', 'weak', 'betont', 'betonte', 'haben', 'C1', 'Ich möchte betonen, wie wichtig das ist.', 'Я хочу подчеркнуть, как это важно.'),
(219, 'bewerten', 'оценивать', 'оцінювати', 'weak', 'bewertet', 'bewertete', 'haben', 'C1', 'Die Schüler bewerten den Unterricht.', 'Ученики оценивают урок.'),
(220, 'bezeichnen', 'обозначать', 'позначати', 'weak', 'bezeichnet', 'bezeichnete', 'haben', 'C1', 'Wie bezeichnet man dieses Phänomen?', 'Как обозначается этот феномен?'),
(221, 'einreichen', 'подавать', 'подавати', 'weak', 'eingereicht', 'reichte ein', 'haben', 'C1', 'Ich reiche die Bewerbung ein.', 'Я подаю заявление.'),
(222, 'erwerben', 'приобретать', 'придбати', 'strong', 'erworben', 'erwarb', 'haben', 'C1', 'Er hat ein Haus erworben.', 'Он приобрел дом.'),
(223, 'erziehen', 'воспитывать', 'виховувати', 'strong', 'erzogen', 'erzog', 'haben', 'C1', 'Eltern erziehen ihre Kinder.', 'Родители воспитывают своих детей.'),
(224, 'gestalten', 'оформлять', 'оформлювати', 'weak', 'gestaltet', 'gestaltete', 'haben', 'C1', 'Wir gestalten den Garten neu.', 'Мы оформляем сад заново.'),
(225, 'gewährleisten', 'гарантировать', 'гарантувати', 'weak', 'gewährleistet', 'gewährleistete', 'haben', 'C1', 'Die Qualität wird gewährleistet.', 'Качество гарантируется.'),
(226, 'herausfordern', 'вызывать', 'викликати', 'weak', 'herausgefordert', 'forderte heraus', 'haben', 'C1', 'Diese Aufgabe fordert mich heraus.', 'Это задание бросает мне вызов.'),
(227, 'nachweisen', 'доказывать', 'доводити', 'strong', 'nachgewiesen', 'wies nach', 'haben', 'C1', 'Der Forscher weist die Theorie nach.', 'Исследователь доказывает теорию.'),
(228, 'schätzen', 'ценить', 'цінувати', 'weak', 'geschätzt', 'schätzte', 'haben', 'C1', 'Ich schätze deine Hilfe sehr.', 'Я очень ценю твою помощь.'),
(229, 'stören', 'мешать', 'заважати', 'weak', 'gestört', 'störte', 'haben', 'C1', 'Die Musik stört mich beim Lernen.', 'Музыка мешает мне учиться.'),
(230, 'teilen', 'делить', 'ділити', 'weak', 'geteilt', 'teilte', 'haben', 'C1', 'Teile deine Meinung mit uns!', 'Поделись своим мнением с нами!'),
(231, 'überraschen', 'удивлять', 'дивувати', 'weak', 'überrascht', 'überraschte', 'haben', 'C1', 'Die Nachricht überrascht mich.', 'Новость меня удивляет.'),
(232, 'überzeugen', 'убеждать', 'переконувати', 'weak', 'überzeugt', 'überzeugte', 'haben', 'C1', 'Ich bin von deiner Idee überzeugt.', 'Я убежден в твоей идее.'),
(233, 'verhalten', 'вести себя', 'поводитися', 'strong', 'verhalten', 'verhielt', 'haben', 'C1', 'Wie verhält man sich in dieser Situation?', 'Как вести себя в этой ситуации?'),
(234, 'verleihen', 'одалживать', 'позичати', 'strong', 'verliehen', 'verlieh', 'haben', 'C1', 'Die Universität verleiht den Titel.', 'Университет присваивает звание.'),
(235, 'vermitteln', 'передавать', 'передавати', 'weak', 'vermittelt', 'vermittelte', 'haben', 'C1', 'Der Kurs vermittelt Grundkenntnisse.', 'Курс передает базовые знания.'),
(236, 'verschaffen', 'доставать', 'діставати', 'weak', 'verschafft', 'verschaffte', 'haben', 'C1', 'Ich verschaffe uns Eintrittskarten.', 'Я достаю нам входные билеты.'),
(237, 'verstärken', 'усиливать', 'посилювати', 'weak', 'verstärkt', 'verstärkte', 'haben', 'C1', 'Wir verstärken das Team.', 'Мы усиливаем команду.'),
(238, 'verteidigen', 'защищать', 'захищати', 'weak', 'verteidigt', 'verteidigte', 'haben', 'C1', 'Der Anwalt verteidigt seinen Mandanten.', 'Адвокат защищает своего клиента.'),
(239, 'voraussetzen', 'предполагать', 'припускати', 'weak', 'vorausgesetzt', 'setzte voraus', 'haben', 'C1', 'Das setzt gute Kenntnisse voraus.', 'Это предполагает хорошие знания.'),
(240, 'weiterentwickeln', 'развивать', 'розвивати', 'weak', 'weiterentwickelt', 'entwickelte weiter', 'haben', 'C1', 'Die Technologie wird weiterentwickelt.', 'Технология развивается дальше.'),
(241, 'widerlegen', 'опровергать', 'спростовувати', 'weak', 'widerlegt', 'widerlegte', 'haben', 'C1', 'Die Theorie wurde widerlegt.', 'Теория была опровергнута.'),
(242, 'zumachen', 'закрывать', 'закривати', 'weak', 'zugemacht', 'machte zu', 'haben', 'C1', 'Mach bitte die Tür zu!', 'Закрой, пожалуйста, дверь!'),
(243, 'zustimmen', 'соглашаться', '', 'weak', 'zugestimmt', 'stimmte zu', 'haben', 'C1', 'Ich stimme dir vollkommen zu.', 'Я с тобой полностью согласен.');
