INSERT OR IGNORE INTO verbs (id, infinitive, translation, type, past_participle, preterite, auxiliary_verb, level, example_sentence, example_translation) VALUES
(1, 'machen', 'делать', 'regular', 'gemacht', 'machte', 'haben', 'A1', 'Ich mache meine Hausaufgaben.', 'Я делаю домашнее задание.'),
(2, 'gehen', 'идти', 'irregular', 'gegangen', 'ging', 'sein', 'A1', 'Wir gehen heute ins Kino.', 'Мы сегодня идем в кино.'),
(3, 'sehen', 'видеть', 'irregular', 'gesehen', 'sah', 'haben', 'A2', 'Sie sieht den Zug.', 'Она видит поезд.'),
(4, 'sein', 'быть', 'irregular', 'gewesen', 'war', 'sein', 'A1', 'Das ist ein Buch.', 'Это книга.'),
(5, 'haben', 'иметь', 'irregular', 'gehabt', 'hatte', 'haben', 'A1', 'Ich habe einen Hund.', 'У меня есть собака.'),
(6, 'werden', 'становиться', 'irregular', 'geworden', 'wurde', 'sein', 'A2', 'Es wird kalt.', 'Становится холодно.'),
(7, 'sagen', 'сказать', 'regular', 'gesagt', 'sagte', 'haben', 'A1', 'Er sagt die Wahrheit.', 'Он говорит правду.'),
(8, 'geben', 'давать', 'irregular', 'gegeben', 'gab', 'haben', 'A1', 'Kannst du mir das Buch geben?', 'Ты можешь дать мне книгу?'),
(9, 'kommen', 'приходить', 'irregular', 'gekommen', 'kam', 'sein', 'A1', 'Kommst du aus Deutschland?', 'Ты из Германии?'),
(10, 'wissen', 'знать', 'irregular', 'gewusst', 'wusste', 'haben', 'A2', 'Ich weiß die Antwort.', 'Я знаю ответ.'),
(11, 'nehmen', 'брать', 'irregular', 'genommen', 'nahm', 'haben', 'A2', 'Nimmst du den Bus?', 'Ты берешь автобус?'),
(12, 'finden', 'находить', 'irregular', 'gefunden', 'fand', 'haben', 'A1', 'Ich finde meine Schlüssel nicht.', 'Я не нахожу свои ключи.'),
(13, 'sprechen', 'говорить', 'irregular', 'gesprochen', 'sprach', 'haben', 'A1', 'Sprichst du Deutsch?', 'Ты говоришь по-немецки?'),
(14, 'lesen', 'читать', 'irregular', 'gelesen', 'las', 'haben', 'A2', 'Ich lese gern Bücher.', 'Я люблю читать книги.'),
(15, 'fahren', 'ехать', 'irregular', 'gefahren', 'fuhr', 'sein', 'A1', 'Wir fahren nach Berlin.', 'Мы едем в Берлин.'),
(16, 'essen', 'есть', 'irregular', 'gegessen', 'aß', 'haben', 'A1', 'Isst du gern Pizza?', 'Ты любишь есть пиццу?'),
(17, 'trinken', 'пить', 'regular', 'getrunken', 'trank', 'haben', 'A1', 'Ich trinke Kaffee.', 'Я пью кофе.'),
(18, 'schlafen', 'спать', 'irregular', 'geschlafen', 'schlief', 'haben', 'A1', 'Das Kind schläft schon.', 'Ребенок уже спит.'),
(19, 'schreiben', 'писать', 'irregular', 'geschrieben', 'schrieb', 'haben', 'A1', 'Ich schreibe einen Brief.', 'Я пишу письмо.'),
(20, 'arbeiten', 'работать', 'regular', 'gearbeitet', 'arbeitete', 'haben', 'A1', 'Er arbeitet in einer Firma.', 'Он работает в фирме.'),
(21, 'heißen', 'называться', 'regular', 'geheißen', 'hieß', 'haben', 'A1', 'Wie heißt du?', 'Как тебя зовут?'),
(22, 'wohnen', 'жить', 'regular', 'gewohnt', 'wohnte', 'haben', 'A1', 'Ich wohne in Berlin.', 'Я живу в Берлине.'),
(23, 'kaufen', 'покупать', 'regular', 'gekauft', 'kaufte', 'haben', 'A1', 'Ich kaufe Brot im Supermarkt.', 'Я покупаю хлеб в супермаркете.'),
(24, 'spielen', 'играть', 'regular', 'gespielt', 'spielte', 'haben', 'A1', 'Die Kinder spielen im Park.', 'Дети играют в парке.'),
(25, 'lernen', 'учить', 'regular', 'gelernt', 'lernte', 'haben', 'A1', 'Ich lerne Deutsch.', 'Я учу немецкий.'),
(26, 'verstehen', 'понимать', 'irregular', 'verstanden', 'verstand', 'haben', 'A2', 'Verstehst du die Frage?', 'Ты понимаешь вопрос?'),
(27, 'helfen', 'помогать', 'irregular', 'geholfen', 'half', 'haben', 'A2', 'Kann ich dir helfen?', 'Я могу тебе помочь?'),
(28, 'bringen', 'приносить', 'irregular', 'gebracht', 'brachte', 'haben', 'A2', 'Bringst du mir Wasser?', 'Ты принесешь мне воды?'),
(29, 'denken', 'думать', 'irregular', 'gedacht', 'dachte', 'haben', 'A2', 'Was denkst du darüber?', 'Что ты об этом думаешь?'),
(30, 'können', 'мочь', 'irregular', 'gekonnt', 'konnte', 'haben', 'A1', 'Ich kann gut schwimmen.', 'Я хорошо умею плавать.'),
(31, 'müssen', 'должен', 'irregular', 'gemusst', 'musste', 'haben', 'A1', 'Ich muss jetzt gehen.', 'Я должен сейчас идти.'),
(32, 'dürfen', 'мочь (разрешение)', 'irregular', 'gedurft', 'durfte', 'haben', 'A2', 'Darf ich hier parken?', 'Мне можно здесь парковаться?'),
(33, 'wollen', 'хотеть', 'irregular', 'gewollt', 'wollte', 'haben', 'A1', 'Ich will Deutsch lernen.', 'Я хочу учить немецкий.'),
(34, 'sollen', 'быть должным', 'irregular', 'gesollt', 'sollte', 'haben', 'A2', 'Soll ich das Fenster öffnen?', 'Мне открыть окно?'),
(35, 'legen', 'класть', 'regular', 'gelegt', 'legte', 'haben', 'B1', 'Ich lege das Buch auf den Tisch.', 'Я кладу книгу на стол.'),
(36, 'liegen', 'лежать', 'irregular', 'gelegen', 'lag', 'haben', 'B1', 'Das Buch liegt auf dem Tisch.', 'Книга лежит на столе.'),
(37, 'stellen', 'ставить', 'regular', 'gestellt', 'stellte', 'haben', 'B1', 'Stell die Tassen auf den Tisch!', 'Поставь чашки на стол!'),
(38, 'stehen', 'стоять', 'irregular', 'gestanden', 'stand', 'haben', 'B1', 'Das Glas steht auf dem Regal.', 'Стакан стоит на полке.'),
(39, 'ziehen', 'тянуть', 'irregular', 'gezogen', 'zog', 'haben', 'B1', 'Der Hund zieht an der Leine.', 'Собака тянет поводок.'),
(40, 'beginnen', 'начинать', 'irregular', 'begonnen', 'begann', 'haben', 'B1', 'Der Unterricht beginnt um neun Uhr.', 'Урок начинается в девять часов.'),
(41, 'vergessen', 'забывать', 'irregular', 'vergessen', 'vergaß', 'haben', 'B1', 'Ich habe meinen Schlüssel vergessen.', 'Я забыл свой ключ.'),
(42, 'erhalten', 'получать', 'irregular', 'erhalten', 'erhielt', 'haben', 'B1', 'Hast du meine Nachricht erhalten?', 'Ты получил мое сообщение?'),
(43, 'bieten', 'предлагать', 'irregular', 'geboten', 'bot', 'haben', 'B2', 'Die Firma bietet gute Leistungen.', 'Фирма предлагает хорошие услуги.'),
(44, 'genießen', 'наслаждаться', 'irregular', 'genossen', 'genoss', 'haben', 'B2', 'Ich genieße das gute Wetter.', 'Я наслаждаюсь хорошей погодой.'),
(45, 'beschreiben', 'описывать', 'irregular', 'beschrieben', 'beschrieb', 'haben', 'B2', 'Kannst du den Weg beschreiben?', 'Ты можешь описать дорогу?'),
(46, 'entwickeln', 'развивать', 'regular', 'entwickelt', 'entwickelte', 'haben', 'B2', 'Das Unternehmen entwickelt neue Produkte.', 'Компания разрабатывает новые продукты.'),
(47, 'entscheiden', 'решать', 'irregular', 'entschieden', 'entschied', 'haben', 'B2', 'Ich muss mich schnell entscheiden.', 'Я должен быстро решиться.'),
(48, 'erscheinen', 'появляться', 'irregular', 'erschienen', 'erschien', 'sein', 'B2', 'Die Sonne erscheint am Horizont.', 'Солнце появляется на горизонте.'),
(49, 'unternehmen', 'предпринимать', 'irregular', 'unternommen', 'unternahm', 'haben', 'B2', 'Was möchtest du heute unternehmen?', 'Что ты хочешь предпринять сегодня?'),
(50, 'vorbereiten', 'готовить', 'regular', 'vorbereitet', 'bereitete vor', 'haben', 'B1', 'Ich bereite mich auf die Prüfung vor.', 'Я готовлюсь к экзамену.');
